### ISSUE TITLE
User registration email

### ISSUE THREAD

**Issue by davisgis** [ArkansasGIS/ArkansasGIS-WP#50]
If one clicks on "Log In" and wants to register, the registration feature states that it will send them an email. We do not have email functionality enabled on WEB1, yet.

**Comment by ArkansasGIS** [comment]
Workaround: Have the user go to the "My Account" page to sign up instead of "Log In"

**Comment by ArkansasGIS** [comment]
RP fixed this issue with Pull Request: https://github.com/ArkansasGIS/ArkansasGIS-WP/pull/57
